In [14]:
import numpy as np
from itertools import permutations

In [15]:
a = [1,1,0,0]
perms = set(permutations(a))
print (perms)

{(1, 0, 1, 0), (1, 1, 0, 0), (1, 0, 0, 1), (0, 1, 1, 0), (0, 1, 0, 1), (0, 0, 1, 1)}


In [70]:
def get_flips(current=[], flip=1):
    p = np.zeros(len(current))
    p[:flip] = 1
    perms = sorted(set(permutations(p)), reverse=True)
    return np.logical_xor(perms, current)

In [71]:
get_flips([0,0,0,0,0])

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]], dtype=bool)

In [72]:
get_flips([0,0,0,0,0], flip=2)

array([[ True,  True, False, False, False],
       [ True, False,  True, False, False],
       [ True, False, False,  True, False],
       [ True, False, False, False,  True],
       [False,  True,  True, False, False],
       [False,  True, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True,  True, False],
       [False, False,  True, False,  True],
       [False, False, False,  True,  True]], dtype=bool)

In [73]:
get_flips([0,0,0,1,1], flip=2)

array([[ True,  True, False,  True,  True],
       [ True, False,  True,  True,  True],
       [ True, False, False, False,  True],
       [ True, False, False,  True, False],
       [False,  True,  True,  True,  True],
       [False,  True, False, False,  True],
       [False,  True, False,  True, False],
       [False, False,  True, False,  True],
       [False, False,  True,  True, False],
       [False, False, False, False, False]], dtype=bool)

In [107]:
def evaluate_solution(candidate, w=w, u=u):
    total_w = np.sum(candidate @ w)
    total_u = np.sum(candidate @ u)
    return total_w, total_u

In [111]:
def knapsack_kflips(weights=w, utilities=u, capacity=c, flips=2):
    visited = {}
    current = [0] * len(weights)
    candidates = get_flips(current, flip=2)
    best_u = 0
    best_cand = list(current)

    for cand in candidates:
        if hash(tuple(cand)) in visited.keys():
            continue
        w, u = evaluate_solution(cand, w=weights, u=utilities)
        visited[hash(tuple(cand))] = (w,u)
        if w>capacity:
            continue
        if best_u<u:
            best_u = u
            best_cand = cand

    return best_cand, visited[hash(tuple(best_cand))]

In [114]:
w = [3,5,1,3,2]
u = [6,7,4,5,6]
c = 6
sack, (weight, utility) = knapsack_kflips(weights=w, utilities=u, capacity=c, flips=2)
print('sack:', sack)
print('weight:', weight)
print('utility:', utility)

sack: [ True False False False  True]
weight: 5
utility: 12
